spring.application.name=school
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwards
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
